server {
    listen 80;
    server_name _;
    client_max_body_size 5M;

    root /usr/share/nginx/html/;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /smartbookhub-api/ {
        proxy_pass http://smartbookhub-backend:3002/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 20s;
        proxy_read_timeout 20s;
        proxy_send_timeout 20s;
        proxy_buffering off;
        proxy_cache off;
    }
 # 旅游助手 - 头像
   location /images/{
   proxy_pass http://smartbookhub-backend:3002/images/;
 proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
expires 1d;
         add_header Cache-Control "public";
}

}
