server {
    listen 80;
    server_name _;
    client_max_body_size 5M;

    root /usr/share/nginx/html/;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /smartbookhub-api/ {
        proxy_pass http://smartbookhub-backend:3002/api/;
       proxy_http_version 1.1;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_buffering off;
         proxy_cache off;
         proxy_connect_timeout 300s;
         proxy_read_timeout 300s;
         proxy_send_timeout 300s;
    }

   location /smartbookhub-img/{
   proxy_pass http://smartbookhub-backend:3002/;
 proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
expires 1d;
         add_header Cache-Control "public";
}

}
